### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by danieldaeschle**
I changed indent from 2 spaces to 4 spaces. I hope it is okay.

PyCharm (shows me PEP errors) doesn't show me any PEP errors or refactoring suggestions anymore expcept of the TODO, which isn't really an error, only a hint :D

I also changed from `camelCase`  to `underscore_case` for variables and methods/functions.
This must be updated in docs.

### CODE REVIEW

**Review by Jaffa — CHANGES_REQUESTED** [review]
Thanks for this! There is example usage in `README.md` and method references in `DEVELOPMENT.md` that need updating too. Is that something you can do?

**Comment by danieldaeschle** [comment]
Yes i will do that.

**Comment by danieldaeschle** [comment]
Ok, please check this.

**Comment by danieldaeschle** [comment]
Still waiting... @Jaffa

**Pull request merged**
